/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DocumentMetadata,  DocumentStructure,  MarkdownSection } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface DocumentMetadata {
        title?: (string | null)
        sourceUrl: ((string | null) | null)
    }
    
    export interface DocumentStructure {
        metadata?: (partial_types.DocumentMetadata | null)
        sections?: (partial_types.MarkdownSection | null)[]
    }
    
    export interface MarkdownSection {
        title?: (string | null)
        level?: (number | null)
        content?: (string | null)
        subsections?: (partial_types.MarkdownSection | null)[]
    }
    
}